apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/ocadmorg/backstage-demo.git
    targetRevision: HEAD
    path: backstage/backstage
    helm:
      values: | 
        cluster-6vx6d.6vx6d.sandbox979.opentlc.com
        # postgresql:
        #   securityContext:
        #     fsGroup: dummy 
        #   containerSecurityContext:
        #     runAsUser: dummy 
        #   volumePermissions:
        #     securityContext:
        #       runAsUser: dummy 
        #   metrics:
        #     securityContext:
        #       runAsUser: dummy
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy